// This file is auto-generated by Lovable. Do not modify it.
// Lovable integration no longer used - using Supabase OAuth directly

export const lovable = {
  auth: {
    signInWithOAuth: async () => {
      throw new Error("Use supabase.auth.signInWithOAuth() instead");
    },
  },
};
